/**
 * Brief educational copy for DOLA "Local Government Type" display labels
 * (`formatLocalGovernmentTypeForDisplay`). Used in the levy detail modal only.
 */

const GOVERNMENT_TYPE_BRIEF_BY_DISPLAY: Record<string, string> = {
  "Airport Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Ambulance district": "An ambulance district is a special district that provides emergency medical transport in its coverage area, often funded in part by property tax.",
  "Boards of Cooperative (Educational) Services (BOCES)": "This is how Colorado classifies this local government in DOLA property-tax records. Compare the name and amounts with your bill or county property tax page.",
  "Business Improvement district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Cemetery district": "A cemetery district is a special district that maintains cemeteries or burial services for its service area.",
  "Charter school": "A charter school here is a public school under state authorization; how it appears on your tax bill depends on how the county ties the levy to that entity.",
  "Cherry Creek Basin Water Quality Authority": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "City & County Of Broomfield": "City and county government combines municipal and county functions in one government; Broomfield is structured this way in state records.",
  "City & County Of Denver": "City and county government combines municipal and county functions in one government; Denver is structured this way in state records.",
  "Colorado New Energy Improvement District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Conservancy Districts (Flood Control)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Conservation Districts (River Water)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Conservation Districts (Soil)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "County": "County government is the general-purpose local government for your county. It levies property tax for county-wide services alongside other districts on your bill.",
  "County Disposal district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "County Housing Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "County Pest Control district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "County Recreation district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "County Revitalization Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Denver Health And Hospital Authority": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Denver Metropolitan Major League Baseball Stadium District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Denver Metropolitan Scientific & Cultural Facilities District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Downtown Development Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Drainage district": "A drainage district is a Colorado special district (Title 32) that manages stormwater or drainage infrastructure for a defined area and may levy property tax for construction and maintenance.",
  "Early Childhood Development Service District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Emergency Telephone Service (911 Authorities)": "This is how Colorado classifies this local government in DOLA property-tax records. Compare the name and amounts with your bill or county property tax page.",
  "Federal Mineral Lease district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Fire Protection district": "A fire protection district is a special district that provides fire and often EMS services in its service area, funded in part by property tax.",
  "Fountain Creek Watershed, Flood Control, and Greenway District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Front Range Passenger Rail District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "General Improvement Districts (Municipal)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Grand Valley Drainage District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Ground Water Management district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Health Service Districts (Hospital)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Home Rule Municipalities": "This label is Colorado's classification for a type of municipal government (city or town). Municipalities levy property tax for city services alongside counties and districts.",
  "Housing Authorities (Municipal)": "This is how Colorado classifies this local government in DOLA property-tax records. Compare the name and amounts with your bill or county property tax page.",
  "Intergovernmental Authorities (separate legal entity)": "This is how Colorado classifies this local government in DOLA property-tax records. Compare the name and amounts with your bill or county property tax page.",
  "Intergovernmental Cooperatives (contractual association)": "This label refers to a contractual association of governments working together; tax treatment depends on the specific arrangement and enabling law.",
  "Irrigation Districts (Irrigation Drainage)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Law Enforcement Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Library district": "A library district is a special district that operates public library services in its legal service area and levies property tax within its boundaries.",
  "Local District College": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Local Improvement Districts (County)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Local Marketing district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Metropolitan district": "A metropolitan district is a Colorado special district (Title 32) that often funds infrastructure and services for a defined area and may levy property tax within its boundaries.",
  "Metropolitan Football Stadium District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Metropolitan Sewage Disposal district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Moffat Tunnel Authority": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Multijurisdictional Housing Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Park & Recreation district": "A park and recreation special district provides parks, trails, and recreation services in its service area and may levy property tax within its boundaries.",
  "Power Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Public Highway Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Public Improvement Districts (County)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Pueblo Depot Activity Development Authority": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Recreation Facility district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Regional Service Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Regional Transportation Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Regional Transportation District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Sanitation district": "A sanitation district is a Colorado special district that provides wastewater or sewer services in its service area and may levy property tax for those services.",
  "School district": "A Colorado school district is a local education government that levies property tax for public schools in its boundaries. It is separate from cities and counties.",
  "Special Improvement District (Intergovernmental Authorities)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Special Improvement Districts (Municipal, Incl. Storm Sewer)": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Special Improvement Districts (Title 32 Special District)": "This label identifies a Colorado special district under Title 32: a local government that delivers specific services in its service area and may levy property tax within its boundaries.",
  "Special Taxing Districts of Home Rule County": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Special Taxing Districts of Home Rule Municipality": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Statutory Cities": "This label is Colorado's classification for a type of municipal government (city or town). Municipalities levy property tax for city services alongside counties and districts.",
  "Statutory Towns": "This label is Colorado's classification for a type of municipal government (city or town). Municipalities levy property tax for city services alongside counties and districts.",
  "Subdistrict of Special District": "This label identifies a Colorado special district under Title 32: a local government that delivers specific services in its service area and may levy property tax within its boundaries.",
  "Territorial Charter Municipalities": "This label is Colorado's classification for a type of municipal government (city or town). Municipalities levy property tax for city services alongside counties and districts.",
  "University Of Colorado Hospital Authority": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Urban Drainage & Flood Control District": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Urban Renewal Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Water & Sanitation district": "This label identifies a Colorado special district or special-purpose district. It serves a defined area and may levy property tax for the services it provides.",
  "Water Authorities": "This label identifies a Colorado authority or special-purpose government. It may levy property tax or other charges depending on its enabling law and the services it provides.",
  "Water Conservancy district": "A water conservancy district is a Colorado special district that manages water resources for a defined area and may use property tax where authorized.",
  "Water district": "A water district is a special district organized to provide water supply or delivery; it may levy property tax within its service area depending on its charter and services.",
};

export function getLocalGovernmentTypeBrief(displayLabel: string | null | undefined): string {
  const t = (displayLabel ?? "").trim();
  if (!t) {
    return "This is how Colorado classifies a local government in state records. Your bill lists who levies this tax.";
  }
  return GOVERNMENT_TYPE_BRIEF_BY_DISPLAY[t] ??
    `In Colorado property-tax records, "${t}" is the state's classification label for this local government. Compare with your bill and official notices.`;
}
